import '../styles/globals.css';
import styles from '../styles/App.module.css'
import Footer from '@/components/Footer';
import NavigationBar from '@/components/NavigationBar';

import { Inter, Montserrat } from 'next/font/google'
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Container } from 'react-bootstrap';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

//const inter = Inter({ subsets: ['latin'] })
// const montserratFont = Montserrat({
//   subsets: ['latin'],
//   variable: '--font-montserrat'
// });

export const metadata = {
  title: 'OT Drivers',
  description: 'Generated by RORE',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <meta name='author' content='OT Drivers' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png" />
        <link rel="manifest" href="favicon/site.webmanifest" />
      </Head>

      <html lang="en">
        <body>
          <div className={`w-full min-h-screen bg-ivory`}>
            <NavigationBar />
            <div className='max-w-[3840px] mx-auto'>
              {children}
            </div>
            <Footer />
          </div>
         </body>
      </html>
    </>
  )
}


